export const AUTHORIZATION_SMS_REQUIRED = 'AUTHORIZATION_SMS_REQUIRED';
export const AUTHORIZATION_SMS_LIMIT_EXCEEDED = 'AUTHORIZATION_SMS_LIMIT_EXCEEDED';

export type ErrorCodes = typeof AUTHORIZATION_SMS_REQUIRED | typeof AUTHORIZATION_SMS_REQUIRED | string;
